# Generated by Django 3.0.5 on 2020-04-23 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.NullBooleanField(),
        ),
    ]
