# Generated by Django 2.0.7 on 2020-04-24 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0002_auto_20200423_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalpoints', models.IntegerField(blank=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competitions')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='submissions',
        ),
        migrations.AddField(
            model_name='submission',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Competitions'),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Question'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='submissions',
            field=models.ManyToManyField(max_length=4, to='competitions.Submission'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
