# Generated by Django 2.0.7 on 2020-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20200426_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
