# Generated by Django 2.0.7 on 2020-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20200426_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
